name: dee-pipeline

on: push

env:
  Node-Version: 18

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     
     - name: docker login
       run: |
        echo "${{secrets.Docker_Username}}" | docker login -u "${{secrets.Docker_Password}}" --password-stdin
        docker image build -t deepik89/node-app:latest .
        docker push deepik89/node-app:latest
